---
title: "A3: Incarceration"
output: html_document
---

### Introduction

Incarceration rates continue to be a problematic topic in the U.S. For this assignment, I want to focus on the black prisoner population rates in Washington, compared to the white prisoner population.  

### Summary Information

First, I calculated the highest black jail rate among prisoners in Washington. The highest jail rate is a rate of **31000** in **Pend Oreille County** in **1998**. I then compared this to the highest white jail rate of **865.49** in **Yakima County** in **2018**. The average jail rate among black prisoners is approx. **1868.63**, and the average jail rate among white prisoners is approx. 261.58, this is an alarming difference of over 1600. Additionally, I calculated the average rate of black prisoners in 1990 (the first year this data was collected), which is approx. **1759.7**. This is compared to 2018, the most recent year in the dataset which lead up to be approx **1052.12**.


### The Dataset

**Who collected the data?** 

This data is collected by the Vera Institute

**How was the data collected or generated?** 

The data was collected using two Bureau of Justice Statistics sources: the Census of Jails and the Annual Survey of Jails. The Annual Survey of Jails, which covers approximately one-third of jails annually and includes many of the largest facilities, provides important insights into trends and variations in incarceration across the United States. The Census of Jails, which is conducted every five to eight years, provides comprehensive data on jail populations and operations.

**Why was the data collected?**

The data was collected with the intention of providing insight into incarceration trends and practices across the United States, which allows researchers to further understand patterns dynamics of jail populations and disparities within the criminal justice system. It is through analyzing data from sources like the Census of Jails and the Annual Survey of Jails, researchers aim to uncover patterns of incarceration, identify areas for reform, and help make informed decisions to address issues related to mass incarceration, racial disparities, and the functioning of the criminal justice system at both state and county level.

**How many observations (rows) are in your data?**  

1131

**How many features (columns) are in the data?**  

23

**What, if any, ethical questions or questions of power do you need to consider when working with this data?**  

Researchers need to be mindful of privacy, bias, and power relations while dealing with incarceration data to make sure their findings don't reinforce stereotypes or hurt vulnerable communities. Morally sound research must prioritize social justice in the criminal justice system by interacting with affected communities and placing a high value on accountability and transparency.


**What are possible limitations or problems with this data?**

This data comes with several potential limitations and problems, such as underreporting, poor data quality, and inconsistent data. These restrictions can result in reinforcement of stereotypes, or incorrect portayals of those in the criminal justice system. Moreover, the depth of the data may be limited by contextual factors that are not fully captured, such as systemic inequalities and variations in sentencing practices. The interpretation of trends and patterns is further complicated by the jurisdictions' selective reporting and the lag in data availability. To tackle these obstacles, consideration of data quality, transparency, and context is necessary. To ensure a more accurate and thorough depiction of incarceration and its effects on people and communities, collaboration and community engagement are crucial.

### Trends Over Time Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The first chart that you will create and include will show the trend over time of your variable/topic. Think carefully about what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Show more than one, but fewer than ~10 trends
  - This may mean showing the same measure for different locations or different racial groups. Think carefully about a meaningful comparison of locations (e.g., the top 10 counties in a state, top 10 states, etc.)
- You must have clear x and y axis labels
- The chart needs a clear title 
- You need a legend for your different line colors and a clear legend title

When we say "clear" or "human readable" titles and labels, that means that you should not just display the variable name.

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Variable Comparison Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The second chart that you will create and include will show how two different (continuous) variables are related to one another. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- You must have clear x and y axis labels
- The chart needs a clear title 
- If you choose to add a color encoding (not required), you need a legend for your different color and a clear legend title

### Map

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The last chart that you will create and include will show how a variable is distributed geographically. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Your map needs a title
- Your color scale needs a legend with a clear label
- Use a map based coordinate system to set the aspect ratio of your map

